version: '3'
services:
  devcontainer:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ./:/workspace/rove
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.Xauthority:/tmp/.Xauthority:rw
    env_file:
      - .env
    command: sleep infinity
    network_mode: "host"
    privileged: true
