version: '3'
services:
  devcontainer:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/workspace/thunderhawk
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.Xauthority:/tmp/.Xauthority:rw
    environment:
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=96
    command: sleep infinity
    network_mode: "host"
    privileged: true