name: ROS2 thunderhawk build
run-name: ${{ github.actor }} is working on ROS2 thunderhawk build
on: [push]
jobs:
  Build_thunderhawk:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install VCS
      run: apt install python3-vcstool -y
    
    - name: Add repositories from thunderhawk.repos
      run: vcs import src < thunderhawk.repos
      
    - name: Build docker compose
      run: |
        docker compose run --user root devcontainer bash -c "colcon build"

